### ISSUE TITLE
Exceptions occurring every game tick

### ISSUE THREAD

**Issue by robmonte** [rsn-INVU/pre-eoc-xp-drops#3]
```
2023-09-10 06:40:24 CDT [Client] WARN  n.r.c.config.ConfigInvocationHandler - Unable to unmarshal preeocxp.displaySkill 
java.lang.IllegalArgumentException: No enum constant net.runelite.api.Skill.OVERALL
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at net.runelite.client.config.ConfigManager.stringToObject(ConfigManager.java:1154)
	at net.runelite.client.config.ConfigInvocationHandler.invoke(ConfigInvocationHandler.java:119)
	at com.sun.proxy.$Proxy261.displaySkill(Unknown Source)
	at com.preeocxp.PreEocXpPlugin.onGameTick(PreEocXpPlugin.java:122)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:211)
	at client.wd(client.java:31948)
	at client.bs(client.java)
	at bm.wh(bm.java:401)
	at bm.run(bm.java:380)
	at java.base/java.lang.Thread.run(Thread.java:832)
2023-09-10 06:40:25 CDT [Client] WARN  n.r.c.config.ConfigInvocationHandler - Unable to unmarshal preeocxp.displaySkill 
java.lang.IllegalArgumentException: No enum constant net.runelite.api.Skill.OVERALL
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at net.runelite.client.config.ConfigManager.stringToObject(ConfigManager.java:1154)
	at net.runelite.client.config.ConfigInvocationHandler.invoke(ConfigInvocationHandler.java:119)
	at com.sun.proxy.$Proxy261.displaySkill(Unknown Source)
	at com.preeocxp.PreEocXpPlugin.onGameTick(PreEocXpPlugin.java:122)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:211)
	at client.wd(client.java:31948)
	at client.bs(client.java)
	at bm.wh(bm.java:401)
	at bm.run(bm.java:380)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

Seems like maybe something changed with the way overall skill level is handled? I noticed this issue but I'm a bit out of the loop at the moment to help with investigating the cause.

**Comment by rsn-INVU** [comment]
Thanks for pointing this out. I'll take a look to see what's changed

**Comment by rsn-INVU** [comment]
It seems the "OVERALL" skill enum was deprecated. 
Will have to find a way around that, but at least we know what's wrong. 👍🏻
